### ISSUE TITLE
Condition on executable binary being available in `PATH`

### ISSUE THREAD

**Issue by str4d** [yanganto/test-with#49]
`#[test_with::file(/path/to/file)]` and `#[test_with::path(/path)]` are useful when you know where on the system the file is expected to be. However, it would also be useful to be able to make tests conditional on some other executable binary being accessible such that `std::process::Command` could run it (e.g. only running a test if `nc` is installed). This could be implemented by using the `which` crate.

**Comment by yanganto** [comment]
Nice feature. :smile:
