### ISSUE TITLE
doctests fail with default features disabled

### ISSUE THREAD

**Issue by jelmer** [yanganto/test-with#80]
I get 25 failures, most related to docstrings for runtime. Happy to provide a PR, but I'm not sure what the best approach here is.

One option would be to add "#[cfg(feature = "runtime")] {" blocks to each of the docstrings, but that seems a bit repetitive.

**Comment by yanganto** [comment]
I use examples of the tests and that is exactly what I run for each test
https://github.com/yanganto/test-with/blob/90ff555c12de7a61d6061da8bb36d9063f992ac2/flake.nix#L33-L49

If you use nix shell, you can type `feature-test` to test all of them.  If you do not want to use nix shell, you can open a working branch and use Github CI to test on the working branch.
And if you want to put `#[cfg(feature = "runtime")] {` inside I do not mind if that is easier from your end.

:)

**Comment by jelmer** [comment]
In that case, will it actually run the docstring tests at all?

I'm running "cargo test --no-default-features", which will also run the docstrings.

**Comment by yanganto** [comment]
No, it didn't.  Thanks for pointing out this.

One of the dev dependencies is missing, I put it back in #81 
Now we can run it with all the features.
`cargo test --all-features`

**Comment by yanganto** [comment]
Hi @jelmer,
Happy New Year.  Do you work on this? Is there any other issue you run into?

**Comment by jelmer** [comment]
Hi @yanganto , I'd already patched the Debian package but I'll take another look when I do the next upload. Let's close this issue if you believe it's been fixed - I can always reopen it if it doesn't work for me?
